import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, SchemaTypes, Types } from 'mongoose';
//TODO: document id is string, WHY user& Document
export type UserDocument = User & Document;

@Schema({ _id: false }) // Don't create a separate ID for this sub-schema
export class RefreshToken {
  @Prop({ required: true, unique: true })
  jti: string; // The unique JWT ID

  @Prop({ required: true })
  expiresAt: Date; // The expiration date of the token
}

@Schema({ timestamps: true })
export class User {
  @Prop({ type: SchemaTypes.ObjectId, auto: true })
  _id: Types.ObjectId; // Auto-generated by Mongoose
  @Prop({ unique: true, required: true })
  email: string;

  @Prop({ required: true })
  password: string; // Store hashed password!

  @Prop({ type: [RefreshToken], default: [] })
  refreshTokens: RefreshToken[]; // Store an array of refresh token objects
}

export const UserSchema = SchemaFactory.createForClass(User);
